#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : intel-compute-runtime
Version  : 20.17.16650
Release  : 43
URL      : https://github.com/intel/compute-runtime/archive/20.17.16650/compute-runtime-20.17.16650.tar.gz
Source0  : https://github.com/intel/compute-runtime/archive/20.17.16650/compute-runtime-20.17.16650.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : MIT
Requires: intel-compute-runtime-bin = %{version}-%{release}
Requires: intel-compute-runtime-data = %{version}-%{release}
Requires: intel-compute-runtime-lib = %{version}-%{release}
Requires: intel-compute-runtime-license = %{version}-%{release}
Requires: intel-gmmlib-lib
Requires: intel-graphics-compiler
Requires: libdrm
Requires: libva
Requires: ocl-icd
Requires: opencl-clang-dev
BuildRequires : buildreq-cmake
BuildRequires : intel-graphics-compiler
BuildRequires : intel-graphics-compiler-dev
BuildRequires : libdrm
BuildRequires : libdrm-dev
BuildRequires : libva
BuildRequires : libva-dev
BuildRequires : ocl-icd
BuildRequires : opencl-clang-dev
BuildRequires : pkg-config
BuildRequires : pkgconfig(igc-opencl)
BuildRequires : pkgconfig(igdgmm)
BuildRequires : pkgconfig(libva)
Patch1: 0001-remove-Werror-from-forced-flags.patch

%description
# Intel(R) Graphics Compute Runtime for oneAPI Level Zero and OpenCL(TM) Driver
## Introduction

%package bin
Summary: bin components for the intel-compute-runtime package.
Group: Binaries
Requires: intel-compute-runtime-data = %{version}-%{release}
Requires: intel-compute-runtime-license = %{version}-%{release}

%description bin
bin components for the intel-compute-runtime package.


%package data
Summary: data components for the intel-compute-runtime package.
Group: Data

%description data
data components for the intel-compute-runtime package.


%package lib
Summary: lib components for the intel-compute-runtime package.
Group: Libraries
Requires: intel-compute-runtime-data = %{version}-%{release}
Requires: intel-compute-runtime-license = %{version}-%{release}

%description lib
lib components for the intel-compute-runtime package.


%package license
Summary: license components for the intel-compute-runtime package.
Group: Default

%description license
license components for the intel-compute-runtime package.


%prep
%setup -q -n compute-runtime-20.17.16650
cd %{_builddir}/compute-runtime-20.17.16650
%patch1 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1588633997
mkdir -p clr-build
pushd clr-build
export GCC_IGNORE_WERROR=1
export CFLAGS="$CFLAGS -fno-lto "
export FCFLAGS="$FFLAGS -fno-lto "
export FFLAGS="$FFLAGS -fno-lto "
export CXXFLAGS="$CXXFLAGS -fno-lto "
%cmake .. -DNEO_DRIVER_VERSION="%{version}" \
-DBUILD_TYPE=Release \
-DSKIP_UNIT_TESTS=1
make  %{?_smp_mflags}  VERBOSE=1
popd

%install
export SOURCE_DATE_EPOCH=1588633997
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/intel-compute-runtime
cp %{_builddir}/compute-runtime-20.17.16650/LICENSE %{buildroot}/usr/share/package-licenses/intel-compute-runtime/47021b8c525fc84a5270553d63104832f4f99648
cp %{_builddir}/compute-runtime-20.17.16650/third_party/metrics_discovery/LICENSE.md %{buildroot}/usr/share/package-licenses/intel-compute-runtime/24ebc22b6e51adf8b01ec0340b69fc7dd2178c1d
cp %{_builddir}/compute-runtime-20.17.16650/third_party/metrics_library/LICENSE.md %{buildroot}/usr/share/package-licenses/intel-compute-runtime/1020f0e93b771814d86731da816eb9f22f2ab7b4
cp %{_builddir}/compute-runtime-20.17.16650/third_party/opencl_headers/LICENSE %{buildroot}/usr/share/package-licenses/intel-compute-runtime/7235f6784b4eae4c40a259dcecc7a20e6c487263
pushd clr-build
%make_install
popd
## Remove excluded files
rm -f %{buildroot}/usr/share/defaults/etc/ld.so.conf.d/libintelopencl.conf
## install_append content
mkdir -p %{buildroot}/usr/share/OpenCL/vendors
mv %{buildroot}/usr/share/defaults/etc/OpenCL/vendors/intel.icd %{buildroot}/usr/share/OpenCL/vendors
## install_append end

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/ocloc

%files data
%defattr(-,root,root,-)
/usr/share/OpenCL/vendors/intel.icd

%files lib
%defattr(-,root,root,-)
/usr/lib64/intel-opencl/libigdrcl.so

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/intel-compute-runtime/1020f0e93b771814d86731da816eb9f22f2ab7b4
/usr/share/package-licenses/intel-compute-runtime/24ebc22b6e51adf8b01ec0340b69fc7dd2178c1d
/usr/share/package-licenses/intel-compute-runtime/47021b8c525fc84a5270553d63104832f4f99648
/usr/share/package-licenses/intel-compute-runtime/7235f6784b4eae4c40a259dcecc7a20e6c487263
